# This is a basic workflow to help you get started with Actions

name: second demo

# Controls when the workflow will run
on: push
jobs:
  my-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script for second demo
        run: echo Hello, world this is my demo on 2 github workflows in same repo!
